In [1]:
# page 3

#Example 1:  The upward velocity of a rocket is given at three different times in Table 1

In [2]:
import pandas as pd
import numpy as np
import scipy
import scipy.linalg as linalg 
import numpy as np

In [16]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex1d.xlsx")
print type(xls)
sheetx=xls.parse(0)
#print sheetx
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
var4=sheetx['dd']
#print ((var1), '\n ',var2, ' \n ',var3)
c=np.array([var1,var2,var3], dtype='float')
c= c.T
d=np.array(var4, dtype='float')
d=d.T
t=c
b=d
Ab = np.hstack([t, b.reshape(-1, 1)])
A=Ab
print A
#now we want to see how A has been factorized, P is the so called Permutation matrix
P, L, U = scipy.linalg.lu(A) 
print U
u=U
a3=1/(u[2][2]/u[2][3])
a21= u[1][3]-(u[1][2])*a3
a2=a21/u[1][1]
a11=u[0][3]-u[0][2]*a3-a2*u[0][1]
a1=a11/u[0][0]
print a1," \n ",a2," \n ",a3

<class 'pandas.io.excel.ExcelFile'>
[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]
[[ 1.44000000e+02  1.20000000e+01  1.00000000e+00  2.79200000e+02]
 [ 0.00000000e+00  2.91666667e+00  8.26388889e-01  5.83277778e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.00000000e-01 -2.17142857e-01]]
0.29047619047618967  
  19.690476190476204  
  1.0857142857142323


In [17]:
t=float(input("enter the value of t "))
y=a1*t*t+a2*t+a3

print y

enter the value of t 12
279.2


In [18]:
# ex 2 naive Gausseliminationto solve
#page 6

In [19]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2d.xlsx")
print type(xls)
sheetx=xls.parse(0)
#print sheetx
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
var4=sheetx['dd']
#print ((var1), '\n ',var2, ' \n ',var3)
c=np.array([var1,var2,var3], dtype='float')
c= c.T
d=np.array(var4, dtype='float')
d=d.T
t=c
b=d
Ab = np.hstack([t, b.reshape(-1, 1)])
A=Ab
print A
#now we want to see how A has been factorized, P is the so called Permutation matrix
P, L, U = scipy.linalg.lu(A) 
print U
u=U
a3=1/(u[2][2]/u[2][3])
a21= u[1][3]-(u[1][2])*a3
a2=a21/u[1][1]
a11=u[0][3]-u[0][2]*a3-a2*u[0][1]
a1=a11/u[0][0]
print a1," \n ",a2," \n ",a3

<class 'pandas.io.excel.ExcelFile'>
[[20.    15.    10.    45.   ]
 [-3.    -2.249  7.     1.751]
 [ 5.     1.     3.     9.   ]]
[[20.         15.         10.         45.        ]
 [ 0.         -2.75        0.5        -2.25      ]
 [ 0.          0.          8.50018182  8.50018182]]
1.0  
  1.0  
  1.0


In [21]:
#Find the LUdecomposition of the 
# page 10 exm 1

In [24]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2.1d.xlsx")
print xls
sheetx=xls.parse(0)
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
c=np.array([var1,var2,var3], dtype='float')
c= c.T
t=c
print t
np.save('mm', t)
Ab=t
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

print "upper  \n  "
print Ab
print me
ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
        
for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')


[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
upper  
  
[[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
[2.56, 5.76, 3.4999999999999987]
 lower is   
  [[1.   0.   0.  ]
 [2.56 1.   0.  ]
 [5.76 3.5  1.  ]]


In [25]:
#print a1
print a2
print a3
print  np.matmul(a3,a2)

[[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
[[1.   0.   0.  ]
 [2.56 1.   0.  ]
 [5.76 3.5  1.  ]]
[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]


page 11
Example 2UsetheLUdecomposition method to
solve the following simultaneous linear equations

In [32]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2.2d.xlsx")
sheetx=xls.parse(0)
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
var4=sheetx['dd']
c=np.array([var1,var2,var3], dtype='float')
c= c.T
d=np.array(var4, dtype='float')
d=d.T
t=c
b=d
np.save('r1',b)
Ab=t
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

print "upper  \n  "
print Ab
print me
ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
                    
#print ccc
for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')

L=a3
b=np.load('r1.npy') 
c=b
print "\n ",c

upper  
  
[[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
[2.56, 5.76, 3.4999999999999987]
 lower is   
  [[1.   0.   0.  ]
 [2.56 1.   0.  ]
 [5.76 3.5  1.  ]]

  [106.8 177.2 279.2]


In [33]:
LU = np.linalg.solve(L,c) 
x=LU
for d in LU:
    print d

106.80000000000001
-96.20799999999998
0.7599999999998379


In [34]:
##final solution 

LU = np.linalg.solve(a2,x) 
p=LU
for d in LU:
    print d

0.29047619047618584
19.69047619047626
1.0857142857140567


In [35]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2.1d.xlsx")
print xls
sheetx=xls.parse(0)
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
c=np.array([var1,var2,var3], dtype='float')
c= c.T
t=c
print t

[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]


page 13
Example 3Use LUdecomposition to find the inverse o

In [70]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2.3d.xlsx")
print xls
sheetx=xls.parse(0)
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']

c=np.array([var1,var2,var3], dtype='float')
c= c.T
t=c
#print t
c=t
print c

[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]


In [66]:
Ab=c
#Ab=np.array([[25,5,1], [64,8,1], [144,12,1]],dtype='float')
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

print "upper  \n  "
print Ab
print me


ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
        

for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')


upper  
  
[[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
[2.56, 5.76, 3.4999999999999987]
 lower is   
  [[1.   0.   0.  ]
 [2.56 1.   0.  ]
 [5.76 3.5  1.  ]]


In [67]:
print a1

[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]


In [71]:
##final mergged block  
b=a1
c=b
Ab=c
#Ab=np.array([[25,5,1], [64,8,1], [144,12,1]],dtype='float')
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

ccc=Ab
np.save('d2', Ab) 

k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
        
            
       
            
#print ccc

for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
#print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')


x=[1,0,0]

LU = np.linalg.solve(a3,x) 
p=LU
#for d in LU:
 #   print d
    
    
    
##final solution 

LU = np.linalg.solve(a2,p) 
p1=LU
for d in LU:
    print d
    
    
    
print "#################   \n \n \n "
    
    
import numpy as np

Ab=np.array([[25,5,1], [64,8,1], [144,12,1]],dtype='float')
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

#print "upper  \n  "
#print Ab
#print me


ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
        
            
       
            
#print ccc

for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
#print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')


x=[0,1,0]

LU = np.linalg.solve(a3,x) 
p=LU
#for d in LU:
 #   print d
    
    
    
##final solution 

LU = np.linalg.solve(a2,p) 
p2=LU
for d in LU:
    print d
    
print "#################   \n \n \n "




import numpy as np

Ab=np.array([[25,5,1], [64,8,1], [144,12,1]],dtype='float')
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

#print "upper  \n  "
#print Ab
#print me


ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
        
            
       
            
#print ccc

for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
#print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')


x=[0,0,1]


LU = np.linalg.solve(a3,x) 
p=LU
#for d in LU:
 #   print d
    
    
    
##final solution 

LU = np.linalg.solve(a2,p) 
p3=LU
for d in LU:
    print d
    


print "#################   \n \n \n "
zz=np.array([[p1],[p2],[p3]])
fm=zz.T


print fm
print "#################   \n \n \n "
print a1
print "#################   \n \n \n "
c=np.matmul(fm,a1)


0.0476190476190477
-0.952380952380954
4.571428571428577
#################   
 
 
 
-0.08333333333333356
1.4166666666666698
-5.00000000000001
#################   
 
 
 
0.0357142857142858
-0.46428571428571536
1.428571428571432
#################   
 
 
 
[[[ 0.04761905 -0.08333333  0.03571429]]

 [[-0.95238095  1.41666667 -0.46428571]]

 [[ 4.57142857 -5.          1.42857143]]]
#################   
 
 
 
[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
#################   
 
 
 


page 17
Example 1The upward velocity of a rocket is given at three different time

In [73]:


xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex3.1d.xlsx")

print xls

sheetx=xls.parse(0)

var1=sheetx['aa']


print (var1)
c=np.array(var1, dtype='float')

#c= c.T
print c




0    1
1    2
2    5
Name: aa, dtype: int64
[1. 2. 5.]


In [76]:
inx=c
#print inx[0],inx[1],inx[2]
a1=inx[0]
a2=inx[1]
a3=inx[2]
print a1,a2,a3

1.0 2.0 5.0


In [77]:
#a1,a2,a3=3.6720,-7.8510,-155.36
n=5
p=1
while p <= n:
    m=[]
    
    print "iteration is ",p
    
    m.append(a1)
    m.append(a2)
    m.append(a3)
    a1=(106.8-5*a2-a3)/25
    a2=(177.2-64*a1-a3)/8
    a3=(279.2-144*a1-12*a2)
    
    print  p," th data solution is  ",a1,a2,a3
    
    print " \n "
    ea1=abs((a1-m[0])/(a1*.01))
    ea2=abs((a2-m[1])/(a2*.01))
    ea3=abs((a3-m[2])/(a3*.01))
    print " and error is ",ea1,ea2,ea3
    
    p=p+1
    
    print " \n ############ \n"
    

        
        
        
    
    
    

iteration is  1
1  th data solution is   3.6719999999999997 -7.850999999999999 -155.35599999999994
 
 
 and error is  72.76688453159042 125.47446185199337 103.21841448029043
 
 ############ 

iteration is  2
2  th data solution is   12.056439999999998 -54.88201999999999 -798.3431199999998
 
 
 and error is  69.543248255704 85.69476852346179 80.54019680159577
 
 ############ 

iteration is  3
3  th data solution is   47.182128799999994 -255.5141404 -3448.856862399999
 
 
 and error is  74.44701986401257 78.52094607598477 76.851949737211
 
 ############ 

iteration is  4
4  th data solution is   193.32910257599997 -1093.3757128079997 -14439.682217247999
 
 
 and error is  75.59491655869445 76.63071006545496 76.11542407574323
 
 ############ 

iteration is  5
5  th data solution is   800.5344312515199 -4577.165172856159 -60071.77602594496
 
 
 and error is  75.84999532452866 76.11238241320159 75.96261810036793
 
 ############ 



page 20 
example --2

In [79]:


xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex3.2d.xlsx")

print xls

sheetx=xls.parse(0)

var1=sheetx['ee']


print (var1)
c=np.array(var1, dtype='float')

#c= c.T
print c
inx=c
#print inx[0],inx[1],inx[2]
a1=inx[0]
a2=inx[1]
a3=inx[2]



0    1
1    0
2    1
Name: ee, dtype: int64
[1. 0. 1.]


In [80]:
#x=np.array([1,0,1],dtype='float')
#print inx[0],inx[1],inx[2]
#a1=x[0]
#a2=x[1]
#a3=x[2]
#a1,a2,a3=1.0000,0.0000,1.000
#a1=float((1-3*a2+5*a3)/12)
#a2=(28-a1-3*a3)/5
#a3=(76-3*a1-7*a2)/13
print a1,a2,a3

1.0 0.0 1.0


In [81]:

n=5
p=1
while p <= n:
    m=[]
    
    print "iteration is ",p
    
    m.append(a1)
    m.append(a2)
    m.append(a3)
    a1=(1-3*a2+5*a3)/12
    a2=(28-a1-3*a3)/5
    a3=(76-3*a1-7*a2)/13
    
    print  p," th data solution is  ",a1,a2,a3
    
    print " \n "
    ea1=abs((a1-m[0])/(a1*.01))
    ea2=abs((a2-m[1])/(a2*.01))
    ea3=abs((a3-m[2])/(a3*.01))
    print " and error is ",ea1,ea2,ea3
    
    p=p+1
    
    print " \n ####### \n"
    


iteration is  1
1  th data solution is   0.5 4.9 3.092307692307692
 
 
 and error is  100.0 100.0 67.66169154228855
 
 ####### 

iteration is  2
2  th data solution is   0.14679487179487158 3.7152564102564107 3.811755424063116
 
 
 and error is  240.61135371179085 31.888608992718858 18.87444633025624
 
 ####### 

iteration is  3
3  th data solution is   0.7427506574621955 3.164396614069691 3.9708439791635053
 
 
 and error is  80.23631883458236 17.408051624675004 4.006416669483518
 
 ####### 

iteration is  4
4  th data solution is   0.946752504467371 3.028143111608423 3.997133900410687
 
 
 and error is  21.54753708520095 4.499572755955247 0.6577193034359122
 
 ####### 

iteration is  5
5  th data solution is   0.9917700139356805 3.0033656569664515 4.0000869507252155
 
 
 and error is  4.539107740277883 0.8249896107221893 0.07382465308642645
 
 ####### 

