In [2]:
from pandas import *
#x = [["A", "B"], ["C", "D"]]
t=[[-33,11,0,24],[11,-38,14,-29],[0,14,-45,-29]]
print DataFrame(t)

    0   1   2   3
0 -33  11   0  24
1  11 -38  14 -29
2   0  14 -45 -29


In [27]:
import numpy as np
print(np.matrix(t))

[[-33  11   0  24]
 [ 11 -38  14 -29]
 [  0  14 -45 -29]]


In [36]:
def like_a_gauss(mat):
	"""
	Changes mat into Reduced Row-Echelon Form.
	"""
	print " as ",(len(mat), len(mat[0]))
	# Let's do forward step first.
	# at the end of this for loop, the matrix is in Row-Echelon format.
	for i in range(min(len(mat), len(mat[0]))):
		# every iteration, ignore one more row and column
		for r in range(i, len(mat)):
			# find the first row with a nonzero entry in first column
			zero_row = mat[r][i] == 0
			if zero_row:
				continue
			# swap current row with first row
			mat[i], mat[r] = mat[r], mat[i]
			# add multiples of the new first row to lower rows so lower
			# entries of first column is zero
			first_row_first_col = mat[i][i]
			for rr in range(i + 1, len(mat)):
				this_row_first = mat[rr][i]
				scalarMultiple = -1 * this_row_first / first_row_first_col
				for cc in range(i, len(mat[0])):
					mat[rr][cc] += mat[i][cc] * scalarMultiple
			break

	# At the end of the forward step
	print(mat)
	# Now reduce
	for i in range(min(len(mat), len(mat[0])) - 1, -1, -1):
		# divide last non-zero row by first non-zero entry
		first_elem_col = -1
		first_elem = -1
		for c in range(len(mat[0])):
			if mat[i][c] == 0:
				continue
			if first_elem_col == -1:
				first_elem_col = c
				first_elem = mat[i][c]
			mat[i][c] /= first_elem
		# add multiples of this row so all numbers above the leading 1 is zero
		for r in range(i):
			this_row_above = mat[r][first_elem_col]
			scalarMultiple = -1 * this_row_above
			for cc in range(len(mat[0])):
				mat[r][cc] += mat[i][cc] * scalarMultiple
		# disregard this row and continue
	print ("Reduced Row-Echelon  ")
	print (np.matrix(mat))


def augment_that_sucker(mat1, mat2):
	"""
	Duct-tape mat2's columns to the right of mat1
	Return a new matrix.
	"""
	retval = []
	for i in range(len(mat1)):
		r = mat1[i]
		newrow = r[:] + mat2[i]
		retval.append(newrow)
	return retval

def from_vector(vector):
	"""
	Convert a vector into a column matrix.
	"""
	retval = []
	for r in vector:
		retval.append([r])
	return retval

def transpose(mat):
	"""
	Return a transposed version of mat.
	"""
	retval = []
	for c in range(len(mat[0])):
		newrow = []
		for r in range(len(mat)):
			newrow.append(mat[r][c])
		retval.append(newrow)
	return retval

# testcase from http://reference.wolfram.com/mathematica/ref/RowReduce.html

mattest = [[-33,11,0,24],[11,-38,14,-29],[0,14,-45,-29]]
#a=[-33 11 0 24;11 -38 14 -29;0 14 -45 -29];
#print "left del \n ",np.matrix(mattest)
print DataFrame(mattest)

mattest2 = from_vector([24,-29,-29])
print DataFrame(mattest2)


mattest3 = augment_that_sucker(mattest, mattest2)
like_a_gauss(mattest3)

print(DataFrame(transpose(mattest3)))

    0   1   2
0 -33  11   0
1  11 -38  14
2   0  14 -45
    0
0  24
1 -29
2 -29
 as  (3, 4)
[[-33, 11, 0, 24], [11, -38, 14, -29], [0, 14, -45, -29]]
Reduced Row-Echelon  
[[  0   0   1   0]
 [  1   0 -13 -13]
 [  0   1  -4  -3]]
   0   1  2
0  0   1  0
1  0   0  1
2  1 -13 -4
3  0 -13 -3


In [37]:
print min(len(mat), len(mat[0]))

NameError: name 'mat' is not defined

In [44]:
mat= [[-3,11,0,6],[4,11,-38,14],[0,6,14,5]]

print(DataFrame(transpose(mattest)))

    0   1   2
0  -3   4   0
1  11  11   6
2   0 -38  14
3   6  14   5


In [45]:
print (len(mat), len(mat[0]))

(3, 4)


In [46]:
for da in mat:
    print type(da)
    print da

<type 'list'>
[-3, 11, 0, 6]
<type 'list'>
[4, 11, -38, 14]
<type 'list'>
[0, 6, 14, 5]


In [47]:
for da in mat[0]:
    print type(da)
    print da

<type 'int'>
-3
<type 'int'>
11
<type 'int'>
0
<type 'int'>
6


In [3]:
import scipy

mat1 = [[-33,11,0,24],[11,-38,14,-29],[0,14,-45,-29]]

In [6]:
#import linalg package of the SciPy module for the LU decomp
import scipy.linalg as linalg 
#import NumPy
import numpy as np
#define A same as before
A = np.array([[2., 1., 1.],[1., 3., 2.],[1., 0., 0.]]) 

#define B
B = np.array([4., 5., 6.]) 

#call the lu_factor function
LU = linalg.lu_factor(A) 

#solve given LU and B
x = linalg.lu_solve(LU, B) 
print "Solutions:\n",x

#we get the same solution as before
#Solutions:
#[  6.  15. -23.] 

#now we want to see how A has been factorized, P is the so called Permutation matrix
P, L, U = scipy.linalg.lu(mat1) 

print P
print U

Solutions:
[  6.  15. -23.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-33.          11.           0.          24.        ]
 [  0.         -34.33333333  14.         -21.        ]
 [  0.           0.         -39.29126214 -37.5631068 ]]


In [7]:

u=U
i3=1/(u[2][2]/u[2][3])

print i3

i21= u[1][3]-(u[1][2])*i3
i2=i21/u[1][1]
print i2

i11=u[0][3]-u[0][2]*i3-i2*u[0][1]

i1=i11/u[0][0]

print i1

0.9560168025698047
1.0014825796886582
-0.39344520070984124
