In [1]:
import pandas as pd
import numpy as np
import scipy
import scipy.linalg as linalg 
import numpy as np

In [2]:
xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex2.2d.xls")
sheetx=xls.parse(0)
var1=sheetx['aa']
var2=sheetx['bb']
var3=sheetx['cc']
var4=sheetx['dd']
c=np.array([var1,var2,var3], dtype='float')
c= c.T
d=np.array(var4, dtype='float')
d=d.T
t=c
b=d
np.save('r1',b)
Ab=t
np.save('d1', Ab) 
aaa=Ab
n = len(Ab)
#print n
me=[]
for i in range(n):
    a = Ab[i]
    #print a,"  ",n

    for j in range(i + 1, n):
        b = Ab[j]
        m = float(a[i] / b[i])
        me.append(1/m)
        Ab[j] = b - (1/m) * a
        #print 'j '," = ",j, b," = ",   m

print "upper  \n  "
print Ab
print me
ccc=Ab
np.save('d2', Ab) 

#for i in range(n):
#    for j in range(n):
#       print i,j
 #       print Ab[i][j]
        
k=0            
for i in range(n):
    for j in range(n):
        if (i > j) :
            ccc[i][j]=me[k]
            k=k+1
        else:
            continue
#print ccc 

for i in range(n):
    for j in range(n):
        if (i == j) :
            ccc[i][j]=1
            
        else:
            continue
                    
#print ccc
for i in range(n):
    for j in range(n):
        if (i < j) :
            ccc[i][j]=0
            
        else:
            continue
print " lower is   \n " ,ccc 

np.save('d3', ccc) 

a1 = np.load('d1.npy')                                   
a2 = np.load('d2.npy')
a3=np.load('d3.npy')

L=a3
b=np.load('r1.npy') 
c=b
print "\n ",c

LU = np.linalg.solve(L,c) 
x=LU
for d in LU:
    print d
    

##final solution 

LU = np.linalg.solve(a2,x) 
p=LU
print "solution is "
for d in LU:
    print d
    
file = open("testfile.txt1","w")  
for d in LU:
    
    file.write("%s  " %d) 

 
file.close()

upper  
  
[[ 4.   1.  -1. ]
 [ 0.   6.5  1.5]
 [ 0.   0.  13. ]]
[0.5, 0.25, -0.5]
 lower is   
  [[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.25 -0.5   1.  ]]

  [ 3. 19. 31.]
3.0
17.5
39.0
solution is 
1.0
2.0
3.0


In [3]:


xls=pd.ExcelFile("/media/ashraful/New Volume/labfiles/ex3.1d.xlsx")

print xls

sheetx=xls.parse(0)

var1=sheetx['aa']


print (var1)
c=np.array(var1, dtype='float')

#c= c.T
print c




0    0
1    0
2    0
Name: aa, dtype: int64
[0. 0. 0.]


In [4]:
inx=c
#print inx[0],inx[1],inx[2]
a1=inx[0]
a2=inx[1]
a3=inx[2]
print a1,a2,a3

0.0 0.0 0.0


In [5]:

n=500000
p=1
while (p <= n):
    m=[]
    
    #print "iteration is ",p
    
    m.append(a1)
    m.append(a2)
    m.append(a3)
    a1=(3-a2+a3)/4
    a2=(19-2*a1-a3)/7
    a3=(31-1*a1+3*a2)/12
    
    ea1=abs((a1-m[0])/(a1*.01))
    ea2=abs((a2-m[1])/(a2*.01))
    ea3=abs((a3-m[2])/(a3*.01))
    if (ea1 == 0.0000000000001 and ea2==0.0000000000001 and ea3==0.0000000000001):
        print p
        break
        
    #print " and error is ",ea1,ea2,ea3
    
    p=p+1
    
ckk=np.array([a1,a2,a3], dtype='float')
for d in ckk:
    print d

1.0
2.0
3.0


In [6]:
file = open("testfile.txt","w")  
for d in ckk:
    
    file.write("%s  " %d) 

 
file.close() 